### ISSUE TITLE
Invalid Version: undefined Exception when installing

### ISSUE THREAD

**Issue by sstainba** [quasarframework/app-extension-apollo#136]
I have the latest Quasar CLI and am attempting to install this extension into a Vue3 Quasar app.  However, after setting the endpoint URL, there is an exception:

`TypeError: Invalid Version: undefined
    at new SemVer (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\semver\classes\semver.js:19:13)
    at compare (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\semver\functions\gte.js:2:30)
    at module.exports (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\@quasar\quasar-app-extension-apollo\src\install.js:9:14)
    at Extension.__runInstallScript (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\@quasar\app-vite\lib\app-extension\Extension.js:338:11)
    at Extension.install (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\@quasar\app-vite\lib\app-extension\Extension.js:177:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (C:\Users\samue\repos\location-management-service\src\Lms.Web\clientApp\node_modules\@quasar\app-vite\lib\cmd\ext.js:57:3)`

**Comment by smolinari** [comment]
Did you follow the v2 docs or v1 docs? Here are the v2 docs.

https://github.com/quasarframework/app-extension-apollo/tree/v2

Scott

**Comment by sstainba** [comment]
> Did you follow the v2 docs or v1 docs? Here are the v2 docs.
> 
> https://github.com/quasarframework/app-extension-apollo/tree/v2
> 
> Scott

Ah, thanks.  The initial link I followed went to the dev branch.  I didn't realize there was a v2.
